'use strict';

const emailGateway     = require('../email-gateway');
const { getConfig }    = require('../../config/cosa.config');
const { createLogger } = require('../logger');

const log = createLogger('ips-alert');

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const NAME       = 'ips_alert';
const RISK_LEVEL = 'read';

/** Default expiry window when autoExpireMinutes is not provided. */
const DEFAULT_EXPIRE_MINUTES = 30;

const INPUT_SCHEMA = {
  type: 'object',
  properties: {
    // Full schema fields (direct invocation)
    severity:            { type: 'string' },
    incidentType:        { type: 'string' },
    evidence:            { type: 'array', items: { type: 'string' } },
    actionsAlreadyTaken: { type: 'string' },
    responseOptions:     { type: 'array', items: { type: 'string' } },
    approvalToken:       { type: 'string' },
    autoExpireMinutes:   { type: 'number' },
    // Legacy fields used by cloudflare-kill fire-and-forget dispatch
    alert_type:          { type: 'string' },
    message:             { type: 'string' },
  },
  required:             [],
  additionalProperties: true,
};

const SCHEMA = {
  description:
    'Send an immediate security escalation email to the operator. ' +
    'Accepts incident severity, type, evidence, actions already taken, and ' +
    'response options. Builds and sends the email synchronously (not queued). ' +
    'Returns sent status, subject, and alert reference.',
  inputSchema: INPUT_SCHEMA,
};

// ---------------------------------------------------------------------------
// Email formatter
// ---------------------------------------------------------------------------

/**
 * Build the plain-text email body for an IPS alert.
 *
 * @param {{
 *   severity: string,
 *   incidentType: string,
 *   evidence: string[],
 *   actionsAlreadyTaken: string,
 *   responseOptions: string[],
 *   approvalToken: string | undefined,
 *   expiresAt: Date,
 *   alertRef: string,
 *   appName: string,
 * }} params
 * @returns {string}
 */
function buildEmailBody({
  severity,
  incidentType,
  evidence,
  actionsAlreadyTaken,
  responseOptions,
  approvalToken,
  expiresAt,
  alertRef,
  appName,
}) {
  const lines = [];

  lines.push('╔══════════════════════════════════════════════════════╗');
  lines.push(`║  COSA SECURITY ALERT — ${severity.toUpperCase().padEnd(28)}║`);
  lines.push('╚══════════════════════════════════════════════════════╝');
  lines.push('');
  lines.push(`Appliance : ${appName}`);
  lines.push(`Alert Ref : ${alertRef}`);
  lines.push(`Issued At : ${new Date().toISOString()}`);
  lines.push(`Expires At: ${expiresAt.toISOString()}`);
  lines.push('');

  lines.push('─── WHAT HAPPENED ────────────────────────────────────────');
  lines.push(incidentType);
  lines.push('');

  lines.push('─── EVIDENCE ─────────────────────────────────────────────');
  if (evidence.length === 0) {
    lines.push('  (none provided)');
  } else {
    for (const item of evidence) {
      lines.push(`  • ${item}`);
    }
  }
  lines.push('');

  lines.push('─── ACTIONS ALREADY TAKEN ────────────────────────────────');
  lines.push(actionsAlreadyTaken || '  (none)');
  lines.push('');

  if (responseOptions.length > 0) {
    lines.push('─── RESPONSE OPTIONS ─────────────────────────────────────');
    lines.push('Reply to this email with one of the following codes:');
    lines.push('');
    for (const option of responseOptions) {
      lines.push(`  • ${option}`);
    }
    if (approvalToken) {
      lines.push('');
      lines.push(`Approval token: ${approvalToken}`);
    }
    lines.push('');
    lines.push(`⚠  Response options expire at ${expiresAt.toISOString()}`);
    lines.push('');
  }

  lines.push('─── AUDIT REFERENCE ──────────────────────────────────────');
  lines.push(`Session / Alert ID : ${alertRef}`);
  lines.push('Full audit trail   : COSA session store (session-store.db)');
  lines.push('');
  lines.push('──────────────────────────────────────────────────────────');
  lines.push('This alert was generated by COSA (Compute-Oriented System Agent).');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

/**
 * @param {{
 *   severity?: string,
 *   incidentType?: string,
 *   evidence?: string[],
 *   actionsAlreadyTaken?: string,
 *   responseOptions?: string[],
 *   approvalToken?: string,
 *   autoExpireMinutes?: number,
 *   // Legacy cloudflare-kill fields
 *   alert_type?: string,
 *   message?: string,
 * }} input
 * @returns {Promise<{ sent: boolean, subject: string, alertRef: string, to: string }>}
 */
async function handler(input) {
  const { appliance } = getConfig();
  const appName        = appliance.appliance?.name ?? 'COSA';
  const operatorEmail  = appliance.operator?.email;

  if (!operatorEmail) {
    throw new Error('ips_alert: operator.email not configured in appliance.yaml');
  }

  // Normalise payload — supports both the full AC schema and the simpler
  // fire-and-forget format used by cloudflare-kill.
  const severity     = (input.severity ?? 'UNKNOWN').toUpperCase();
  const incidentType = input.incidentType
    ?? (input.alert_type ? `${input.alert_type}: ${input.message ?? ''}`.trim() : 'Security incident');
  const evidence            = Array.isArray(input.evidence) ? input.evidence
    : (input.message ? [input.message] : []);
  const actionsAlreadyTaken = input.actionsAlreadyTaken ?? '';
  const responseOptions     = Array.isArray(input.responseOptions) ? input.responseOptions : [];
  const approvalToken       = input.approvalToken;
  const expireMinutes       = typeof input.autoExpireMinutes === 'number'
    ? input.autoExpireMinutes
    : DEFAULT_EXPIRE_MINUTES;

  const expiresAt = new Date(Date.now() + expireMinutes * 60 * 1000);

  // Unique reference for audit trail — timestamp-based, monotonically increasing.
  const alertRef = `IPS-${Date.now()}`;

  const subject = `[COSA SECURITY] ${severity}: ${incidentType}`;

  const body = buildEmailBody({
    severity,
    incidentType,
    evidence,
    actionsAlreadyTaken,
    responseOptions,
    approvalToken,
    expiresAt,
    alertRef,
    appName,
  });

  log.warn(`Sending IPS alert: ${subject} → ${operatorEmail}`);

  // Send immediately — not queued for cron.
  await emailGateway.sendEmail({ to: operatorEmail, subject, text: body });

  log.info(`IPS alert sent: ${alertRef}`);

  return {
    sent:     true,
    subject,
    alertRef,
    to:       operatorEmail,
  };
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = { name: NAME, schema: SCHEMA, handler, riskLevel: RISK_LEVEL };
